# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc832762ab26c610d24ed373d158bfe744e5b0c0d393195c9f9ae67a6fd19ef86c0626f925fa37d6b5ff46bf01323af92f6aeb55f707b0d036cd5389d30145b

test:
  secret_key_base: 06c6fe52de4ddace948337d70b15a687fc171228c218e06edcc6df6028b31ce509d3e63e58ccc55919af34ec609c7a5159b2ba1953e24e2fb12fce307c0372a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
