# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0001_initial'),
        ('appintegrate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='num_users',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='title',
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginandreg.User'),
        ),
    ]
