# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db84abff49fdc68ab2f5d82885233340573256d6d603a89668053bb161f0835675f294347bb1771c76a12796f8a32610d7de35555e8ba630a0b63e30db98d8a1

test:
  secret_key_base: c008a4f1e876960eadf88b3abea3eea016a2f7bd31984cd45a41fb0692e28e5586fbf815a8157ee10a8716a315aef54f1de81dbb2e4a359503f0ab4826d59286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
