# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cbfd1168ae5bbec06c8b0dc54ab1ff3f4d568825646df52bfe6830462ea88c3091d1c2d7bd02a87f6927f6e5a80ddf7289f2fc3b9e7cd29f338484d886c839c

test:
  secret_key_base: dcd6f551c56624f4811c68baceca3984c46e5165535fa63fb8ebdd40eadca4585cc56e6ab1fb1bd2193adaf087c2166abb1482d6a1d71eeab4609abd1dc7dbb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
